package gui;

public class Visibility implements IScenes
{
	private boolean isVisible;

	protected Visibility(boolean isVisible)
	{
		this.isVisible = isVisible;
	}

	@Override
	public void main()
	{
		Screen.appLabel.setVisible(isVisible);
		Screen.goMovies.setVisible(isVisible);
		Screen.goShows.setVisible(isVisible);
		Screen.goWatchlist.setVisible(isVisible);
		Screen.goStats.setVisible(isVisible);
		Screen.goSettings.setVisible(isVisible);
	}

	@Override
	public void moviesScene()
	{
		Screen.moviesPrompt.setVisible(isVisible);
		Screen.movieName1.setVisible(isVisible);
		Screen.movieName2.setVisible(isVisible);
		Screen.movieName3.setVisible(isVisible);
		Screen.movieName4.setVisible(isVisible);
		Screen.movieName5.setVisible(isVisible);
		Screen.movieName6.setVisible(isVisible);
		Screen.movieName7.setVisible(isVisible);
		Screen.movieName8.setVisible(isVisible);
		Screen.movieName9.setVisible(isVisible);
		Screen.movieName10.setVisible(isVisible);
		Screen.searchMovieBar.setVisible(isVisible);
		Screen.openMovie1.setVisible(isVisible);
		Screen.openMovie2.setVisible(isVisible);
		Screen.openMovie3.setVisible(isVisible);
		Screen.openMovie4.setVisible(isVisible);
		Screen.openMovie5.setVisible(isVisible);
		Screen.openMovie6.setVisible(isVisible);
		Screen.openMovie7.setVisible(isVisible);
		Screen.openMovie8.setVisible(isVisible);
		Screen.openMovie9.setVisible(isVisible);
		Screen.openMovie10.setVisible(isVisible);
		Screen.deleteMovie1.setVisible(isVisible);
		Screen.deleteMovie2.setVisible(isVisible);
		Screen.deleteMovie3.setVisible(isVisible);
		Screen.deleteMovie4.setVisible(isVisible);
		Screen.deleteMovie5.setVisible(isVisible);
		Screen.deleteMovie6.setVisible(isVisible);
		Screen.deleteMovie7.setVisible(isVisible);
		Screen.deleteMovie8.setVisible(isVisible);
		Screen.deleteMovie9.setVisible(isVisible);
		Screen.deleteMovie10.setVisible(isVisible);
		Screen.quitMovies.setVisible(isVisible);
		Screen.nextMoviePage.setVisible(isVisible);
		Screen.prevMoviePage.setVisible(isVisible);
		Screen.addMovie.setVisible(isVisible);
		Screen.movieScores1.setVisible(isVisible);
		Screen.movieScores2.setVisible(isVisible);
		Screen.movieScores3.setVisible(isVisible);
		Screen.movieScores4.setVisible(isVisible);
		Screen.movieScores5.setVisible(isVisible);
		Screen.movieScores6.setVisible(isVisible);
		Screen.movieScores7.setVisible(isVisible);
		Screen.movieScores8.setVisible(isVisible);
		Screen.movieScores9.setVisible(isVisible);
		Screen.movieScores10.setVisible(isVisible);
	}

	@Override
	public void addMovieScene()
	{
		Screen.addMovieNamePrompt.setVisible(isVisible);
		Screen.addMovieDatePrompt.setVisible(isVisible);
		Screen.addMovieDirectorPrompt.setVisible(isVisible);
		Screen.addMovieLengthPrompt.setVisible(isVisible);
		Screen.addMovieScorePrompt.setVisible(isVisible);
		Screen.addMovieReviewPrompt.setVisible(isVisible);
		Screen.addMovieNameInput.setVisible(isVisible);
		Screen.addMovieDateInput.setVisible(isVisible);
		Screen.addMovieDirectorInput.setVisible(isVisible);
		Screen.addMovieLengthInput.setVisible(isVisible);
		Screen.addMovieReviewInput.setVisible(isVisible);
		Screen.addMovieClear.setVisible(isVisible);
		Screen.addMovieCancel.setVisible(isVisible);
		Screen.addMovieSave.setVisible(isVisible);
		Screen.addMovieScores.setVisible(isVisible);
	}

	@Override
	public void movieInfoScene()
	{
		Screen.movieInfoName.setVisible(isVisible);
		Screen.movieInfoDate.setVisible(isVisible);
		Screen.movieInfoDirector.setVisible(isVisible);
		Screen.movieInfoLength.setVisible(isVisible);
		Screen.movieInfoReview.setVisible(isVisible);
		Screen.movieInfoBack.setVisible(isVisible);
		Screen.movieInfoEdit.setVisible(isVisible);
		Screen.movieInfoScore.setVisible(isVisible);
	}

	@Override
	public void showsScene()
	{
		Screen.showsPrompt.setVisible(isVisible);
		Screen.showsSearchBar.setVisible(isVisible);
		Screen.showsProgress1.setVisible(isVisible);
		Screen.showsProgress2.setVisible(isVisible);
		Screen.showsProgress3.setVisible(isVisible);
		Screen.showsProgress4.setVisible(isVisible);
		Screen.showsProgress5.setVisible(isVisible);
		Screen.showsProgress6.setVisible(isVisible);
		Screen.showsProgress7.setVisible(isVisible);
		Screen.showsProgress8.setVisible(isVisible);
		Screen.showsProgress9.setVisible(isVisible);
		Screen.showsProgress10.setVisible(isVisible);
		Screen.showsName1.setVisible(isVisible);
		Screen.showsName2.setVisible(isVisible);
		Screen.showsName3.setVisible(isVisible);
		Screen.showsName4.setVisible(isVisible);
		Screen.showsName5.setVisible(isVisible);
		Screen.showsName6.setVisible(isVisible);
		Screen.showsName7.setVisible(isVisible);
		Screen.showsName8.setVisible(isVisible);
		Screen.showsName9.setVisible(isVisible);
		Screen.showsName10.setVisible(isVisible);
		Screen.showsOpen1.setVisible(isVisible);
		Screen.showsOpen2.setVisible(isVisible);
		Screen.showsOpen3.setVisible(isVisible);
		Screen.showsOpen4.setVisible(isVisible);
		Screen.showsOpen5.setVisible(isVisible);
		Screen.showsOpen6.setVisible(isVisible);
		Screen.showsOpen7.setVisible(isVisible);
		Screen.showsOpen8.setVisible(isVisible);
		Screen.showsOpen9.setVisible(isVisible);
		Screen.showsOpen10.setVisible(isVisible);
		Screen.showsDelete1.setVisible(isVisible);
		Screen.showsDelete2.setVisible(isVisible);
		Screen.showsDelete3.setVisible(isVisible);
		Screen.showsDelete4.setVisible(isVisible);
		Screen.showsDelete5.setVisible(isVisible);
		Screen.showsDelete6.setVisible(isVisible);
		Screen.showsDelete7.setVisible(isVisible);
		Screen.showsDelete8.setVisible(isVisible);
		Screen.showsDelete9.setVisible(isVisible);
		Screen.showsDelete10.setVisible(isVisible);
		Screen.showsAdd.setVisible(isVisible);
		Screen.showsNext.setVisible(isVisible);
		Screen.showsPrevious.setVisible(isVisible);
		Screen.quitShows.setVisible(isVisible);
	}

	@Override
	public void addShowsScene()
	{
		Screen.addShowNamePrompt.setVisible(isVisible);
		Screen.addShowLengthPrompt.setVisible(isVisible);
		Screen.addShowScorePrompt.setVisible(isVisible);
		Screen.addShowSeasonsPrompt.setVisible(isVisible);
		Screen.addShowNameInput.setVisible(isVisible);
		Screen.addShowLengthInput.setVisible(isVisible);
		Screen.addShowScoreInput.setVisible(isVisible);
		Screen.addShowClear.setVisible(isVisible);
		Screen.addShowCancel.setVisible(isVisible);
		Screen.addShowSave.setVisible(isVisible);
		Screen.addShowSeasonsInput.setVisible(isVisible);
	}

	@Override
	public void showsInfoScene()
	{
		Screen.showsInfoName.setVisible(isVisible);
		Screen.showsInfoLength.setVisible(isVisible);
		Screen.showsInfoSeasons.setVisible(isVisible);
		Screen.showsInfoBack.setVisible(isVisible);
		Screen.showsInfoWatchEp.setVisible(isVisible);
		Screen.showsInfoEdit.setVisible(isVisible);
		Screen.showsInfoScores.setVisible(isVisible);
		Screen.showsInfoSitu.setVisible(isVisible);
	}

	@Override
	public void watchlistScene()
	{
		Screen.watchlistPrompt.setVisible(isVisible);
		Screen.watchlistName1.setVisible(isVisible);
		Screen.watchlistName2.setVisible(isVisible);
		Screen.watchlistName3.setVisible(isVisible);
		Screen.watchlistName4.setVisible(isVisible);
		Screen.watchlistName5.setVisible(isVisible);
		Screen.watchlistName6.setVisible(isVisible);
		Screen.watchlistName7.setVisible(isVisible);
		Screen.watchlistName8.setVisible(isVisible);
		Screen.watchlistName9.setVisible(isVisible);
		Screen.watchlistName10.setVisible(isVisible);
		Screen.watchlistType1.setVisible(isVisible);
		Screen.watchlistType2.setVisible(isVisible);
		Screen.watchlistType3.setVisible(isVisible);
		Screen.watchlistType4.setVisible(isVisible);
		Screen.watchlistType5.setVisible(isVisible);
		Screen.watchlistType6.setVisible(isVisible);
		Screen.watchlistType7.setVisible(isVisible);
		Screen.watchlistType8.setVisible(isVisible);
		Screen.watchlistType9.setVisible(isVisible);
		Screen.watchlistType10.setVisible(isVisible);
		Screen.watchlistSearchBar.setVisible(isVisible);
		Screen.watchlistAdd.setVisible(isVisible);
		Screen.watchlistNext.setVisible(isVisible);
		Screen.watchlistPrev.setVisible(isVisible);
		Screen.watchlistStart1.setVisible(isVisible);
		Screen.watchlistStart2.setVisible(isVisible);
		Screen.watchlistStart3.setVisible(isVisible);
		Screen.watchlistStart4.setVisible(isVisible);
		Screen.watchlistStart5.setVisible(isVisible);
		Screen.watchlistStart6.setVisible(isVisible);
		Screen.watchlistStart7.setVisible(isVisible);
		Screen.watchlistStart8.setVisible(isVisible);
		Screen.watchlistStart9.setVisible(isVisible);
		Screen.watchlistStart10.setVisible(isVisible);
		Screen.watchlistDelete1.setVisible(isVisible);
		Screen.watchlistDelete2.setVisible(isVisible);
		Screen.watchlistDelete3.setVisible(isVisible);
		Screen.watchlistDelete4.setVisible(isVisible);
		Screen.watchlistDelete5.setVisible(isVisible);
		Screen.watchlistDelete6.setVisible(isVisible);
		Screen.watchlistDelete7.setVisible(isVisible);
		Screen.watchlistDelete8.setVisible(isVisible);
		Screen.watchlistDelete9.setVisible(isVisible);
		Screen.watchlistDelete10.setVisible(isVisible);
		Screen.quitWatchlist.setVisible(isVisible);
	}

	@Override
	public void watchlistAddScene()
	{
		Screen.watchlistAddNamePrompt.setVisible(isVisible);
		Screen.watchlistAddTypePrompt.setVisible(isVisible);
		Screen.watchlistAddNameInput.setVisible(isVisible);
		Screen.watchlistAddClear.setVisible(isVisible);
		Screen.watchlistAddSave.setVisible(isVisible);
		Screen.watchlistAddCancel.setVisible(isVisible);
		Screen.watchlistAddTypeSet.setVisible(isVisible);
	}

	@Override
	public void statsScene()
	{
		Screen.statsPrompt.setVisible(isVisible);
		Screen.statsInfo.setVisible(isVisible);
		Screen.quitStats.setVisible(isVisible);
	}

	@Override
	public void settingsScene()
	{
		Screen.settingsPrompt.setVisible(isVisible);
		Screen.settingsLanguagePrompt.setVisible(isVisible);
		Screen.settingsThemePrompt.setVisible(isVisible);
		Screen.settingsDatePrompt.setVisible(isVisible);
		Screen.settingsHelp.setVisible(isVisible);
		Screen.settingsImport.setVisible(isVisible);
		Screen.settingsExport.setVisible(isVisible);
		Screen.quitSettings.setVisible(isVisible);
		Screen.settingsLanguageSet.setVisible(isVisible);
		Screen.settingsThemeSet.setVisible(isVisible);
		Screen.settingsDateSet.setVisible(isVisible);
	}

	@Override
	public void helpScene()
	{
		Screen.helpPrompt.setVisible(isVisible);
		Screen.helpInfo.setVisible(isVisible);
		Screen.helpNext.setVisible(isVisible);
		Screen.helpPrev.setVisible(isVisible);
		Screen.quitHelp.setVisible(isVisible);
	}

	protected void launch()
	{
		Screen.appLabel.setVisible(false);
		Screen.goMovies.setVisible(false);
		Screen.goShows.setVisible(false);
		Screen.goWatchlist.setVisible(false);
		Screen.goStats.setVisible(false);
		Screen.goSettings.setVisible(false);
		Screen.moviesPrompt.setVisible(false);
		Screen.movieName1.setVisible(false);
		Screen.movieName2.setVisible(false);
		Screen.movieName3.setVisible(false);
		Screen.movieName4.setVisible(false);
		Screen.movieName5.setVisible(false);
		Screen.movieName6.setVisible(false);
		Screen.movieName7.setVisible(false);
		Screen.movieName8.setVisible(false);
		Screen.movieName9.setVisible(false);
		Screen.movieName10.setVisible(false);
		Screen.searchMovieBar.setVisible(false);
		Screen.openMovie1.setVisible(false);
		Screen.openMovie2.setVisible(false);
		Screen.openMovie3.setVisible(false);
		Screen.openMovie4.setVisible(false);
		Screen.openMovie5.setVisible(false);
		Screen.openMovie6.setVisible(false);
		Screen.openMovie7.setVisible(false);
		Screen.openMovie8.setVisible(false);
		Screen.openMovie9.setVisible(false);
		Screen.openMovie10.setVisible(false);
		Screen.deleteMovie1.setVisible(false);
		Screen.deleteMovie2.setVisible(false);
		Screen.deleteMovie3.setVisible(false);
		Screen.deleteMovie4.setVisible(false);
		Screen.deleteMovie5.setVisible(false);
		Screen.deleteMovie6.setVisible(false);
		Screen.deleteMovie7.setVisible(false);
		Screen.deleteMovie8.setVisible(false);
		Screen.deleteMovie9.setVisible(false);
		Screen.deleteMovie10.setVisible(false);
		Screen.quitMovies.setVisible(false);
		Screen.nextMoviePage.setVisible(false);
		Screen.prevMoviePage.setVisible(false);
		Screen.addMovie.setVisible(false);
		Screen.movieScores1.setVisible(false);
		Screen.movieScores2.setVisible(false);
		Screen.movieScores3.setVisible(false);
		Screen.movieScores4.setVisible(false);
		Screen.movieScores5.setVisible(false);
		Screen.movieScores6.setVisible(false);
		Screen.movieScores7.setVisible(false);
		Screen.movieScores8.setVisible(false);
		Screen.movieScores9.setVisible(false);
		Screen.movieScores10.setVisible(false);
		Screen.addMovieNamePrompt.setVisible(false);
		Screen.addMovieDatePrompt.setVisible(false);
		Screen.addMovieDirectorPrompt.setVisible(false);
		Screen.addMovieLengthPrompt.setVisible(false);
		Screen.addMovieScorePrompt.setVisible(false);
		Screen.addMovieReviewPrompt.setVisible(false);
		Screen.addMovieNameInput.setVisible(false);
		Screen.addMovieDateInput.setVisible(false);
		Screen.addMovieDirectorInput.setVisible(false);
		Screen.addMovieLengthInput.setVisible(false);
		Screen.addMovieReviewInput.setVisible(false);
		Screen.addMovieClear.setVisible(false);
		Screen.addMovieCancel.setVisible(false);
		Screen.addMovieSave.setVisible(false);
		Screen.addMovieScores.setVisible(false);
		Screen.movieInfoName.setVisible(false);
		Screen.movieInfoDate.setVisible(false);
		Screen.movieInfoDirector.setVisible(false);
		Screen.movieInfoLength.setVisible(false);
		Screen.movieInfoReview.setVisible(false);
		Screen.movieInfoBack.setVisible(false);
		Screen.movieInfoEdit.setVisible(false);
		Screen.movieInfoScore.setVisible(false);
		Screen.showsPrompt.setVisible(false);
		Screen.showsSearchBar.setVisible(false);
		Screen.showsProgress1.setVisible(false);
		Screen.showsProgress2.setVisible(false);
		Screen.showsProgress3.setVisible(false);
		Screen.showsProgress4.setVisible(false);
		Screen.showsProgress5.setVisible(false);
		Screen.showsProgress6.setVisible(false);
		Screen.showsProgress7.setVisible(false);
		Screen.showsProgress8.setVisible(false);
		Screen.showsProgress9.setVisible(false);
		Screen.showsProgress10.setVisible(false);
		Screen.showsName1.setVisible(false);
		Screen.showsName2.setVisible(false);
		Screen.showsName3.setVisible(false);
		Screen.showsName4.setVisible(false);
		Screen.showsName5.setVisible(false);
		Screen.showsName6.setVisible(false);
		Screen.showsName7.setVisible(false);
		Screen.showsName8.setVisible(false);
		Screen.showsName9.setVisible(false);
		Screen.showsName10.setVisible(false);
		Screen.showsOpen1.setVisible(false);
		Screen.showsOpen2.setVisible(false);
		Screen.showsOpen3.setVisible(false);
		Screen.showsOpen4.setVisible(false);
		Screen.showsOpen5.setVisible(false);
		Screen.showsOpen6.setVisible(false);
		Screen.showsOpen7.setVisible(false);
		Screen.showsOpen8.setVisible(false);
		Screen.showsOpen9.setVisible(false);
		Screen.showsOpen10.setVisible(false);
		Screen.showsDelete1.setVisible(false);
		Screen.showsDelete2.setVisible(false);
		Screen.showsDelete3.setVisible(false);
		Screen.showsDelete4.setVisible(false);
		Screen.showsDelete5.setVisible(false);
		Screen.showsDelete6.setVisible(false);
		Screen.showsDelete7.setVisible(false);
		Screen.showsDelete8.setVisible(false);
		Screen.showsDelete9.setVisible(false);
		Screen.showsDelete10.setVisible(false);
		Screen.showsAdd.setVisible(false);
		Screen.showsNext.setVisible(false);
		Screen.showsPrevious.setVisible(false);
		Screen.quitShows.setVisible(false);
		Screen.addShowNamePrompt.setVisible(false);
		Screen.addShowLengthPrompt.setVisible(false);
		Screen.addShowScorePrompt.setVisible(false);
		Screen.addShowSeasonsPrompt.setVisible(false);
		Screen.addShowNameInput.setVisible(false);
		Screen.addShowLengthInput.setVisible(false);
		Screen.addShowScoreInput.setVisible(false);
		Screen.addShowClear.setVisible(false);
		Screen.addShowCancel.setVisible(false);
		Screen.addShowSave.setVisible(false);
		Screen.addShowSeasonsInput.setVisible(false);
		Screen.showsInfoName.setVisible(false);
		Screen.showsInfoLength.setVisible(false);
		Screen.showsInfoSeasons.setVisible(false);
		Screen.showsInfoBack.setVisible(false);
		Screen.showsInfoWatchEp.setVisible(false);
		Screen.showsInfoEdit.setVisible(false);
		Screen.showsInfoScores.setVisible(false);
		Screen.showsInfoSitu.setVisible(false);
		Screen.watchlistPrompt.setVisible(false);
		Screen.watchlistName1.setVisible(false);
		Screen.watchlistName2.setVisible(false);
		Screen.watchlistName3.setVisible(false);
		Screen.watchlistName4.setVisible(false);
		Screen.watchlistName5.setVisible(false);
		Screen.watchlistName6.setVisible(false);
		Screen.watchlistName7.setVisible(false);
		Screen.watchlistName8.setVisible(false);
		Screen.watchlistName9.setVisible(false);
		Screen.watchlistName10.setVisible(false);
		Screen.watchlistType1.setVisible(false);
		Screen.watchlistType2.setVisible(false);
		Screen.watchlistType3.setVisible(false);
		Screen.watchlistType4.setVisible(false);
		Screen.watchlistType5.setVisible(false);
		Screen.watchlistType6.setVisible(false);
		Screen.watchlistType7.setVisible(false);
		Screen.watchlistType8.setVisible(false);
		Screen.watchlistType9.setVisible(false);
		Screen.watchlistType10.setVisible(false);
		Screen.watchlistSearchBar.setVisible(false);
		Screen.watchlistAdd.setVisible(false);
		Screen.watchlistNext.setVisible(false);
		Screen.watchlistPrev.setVisible(false);
		Screen.watchlistStart1.setVisible(false);
		Screen.watchlistStart2.setVisible(false);
		Screen.watchlistStart3.setVisible(false);
		Screen.watchlistStart4.setVisible(false);
		Screen.watchlistStart5.setVisible(false);
		Screen.watchlistStart6.setVisible(false);
		Screen.watchlistStart7.setVisible(false);
		Screen.watchlistStart8.setVisible(false);
		Screen.watchlistStart9.setVisible(false);
		Screen.watchlistStart10.setVisible(false);
		Screen.watchlistDelete1.setVisible(false);
		Screen.watchlistDelete2.setVisible(false);
		Screen.watchlistDelete3.setVisible(false);
		Screen.watchlistDelete4.setVisible(false);
		Screen.watchlistDelete5.setVisible(false);
		Screen.watchlistDelete6.setVisible(false);
		Screen.watchlistDelete7.setVisible(false);
		Screen.watchlistDelete8.setVisible(false);
		Screen.watchlistDelete9.setVisible(false);
		Screen.watchlistDelete10.setVisible(false);
		Screen.quitWatchlist.setVisible(false);
		Screen.watchlistAddNamePrompt.setVisible(false);
		Screen.watchlistAddTypePrompt.setVisible(false);
		Screen.watchlistAddNamePrompt.setVisible(false);
		Screen.watchlistAddNameInput.setVisible(false);
		Screen.watchlistAddClear.setVisible(false);
		Screen.watchlistAddSave.setVisible(false);
		Screen.watchlistAddCancel.setVisible(false);
		Screen.watchlistAddTypeSet.setVisible(false);
		Screen.statsPrompt.setVisible(false);
		Screen.statsInfo.setVisible(false);
		Screen.quitStats.setVisible(false);
		Screen.settingsPrompt.setVisible(false);
		Screen.settingsLanguagePrompt.setVisible(false);
		Screen.settingsThemePrompt.setVisible(false);
		Screen.settingsDatePrompt.setVisible(false);
		Screen.settingsHelp.setVisible(false);
		Screen.settingsImport.setVisible(false);
		Screen.settingsExport.setVisible(false);
		Screen.quitSettings.setVisible(false);
		Screen.settingsLanguageSet.setVisible(false);
		Screen.settingsThemeSet.setVisible(false);
		Screen.settingsDateSet.setVisible(false);
		Screen.helpPrompt.setVisible(false);
		Screen.helpInfo.setVisible(false);
		Screen.helpNext.setVisible(false);
		Screen.helpPrev.setVisible(false);
		Screen.quitHelp.setVisible(false);
	}

}